### ISSUE TITLE
auto farm not working please fix it

### ISSUE THREAD

**Issue by Rifkichrl** [dante4rt/fintopio-airdrop-bot#4]
I've tried cloning several times, but auto farm doesn't work

**Comment by dante4rt** [comment]
Fixed in https://github.com/dante4rt/fintopio-airdrop-bot/commit/9eec78ae38609dc70a09415921b08d361e719ef8

**Comment by nguyenanh29** [comment]
Works like a charm! Thanks boss 😍😍😍
